dist: xenial
language: node_js
node_js:
- lts/*
cache:
  directories:
    - '$HOME/google-cloud-sdk'
    - '/tmp/.npm'
    - '~/.cache'
branches:
  only:
  - main
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - HELM_VERSION=v3.5.4
  - REGION=us-central1
  - GRAPHQL_REPO_NAME=graphql-schema-registry
  - GRAPHQL_REPO_ORG=pipedrive
  - GRAPHQL_REPO_TAG=1.2.4
  - DOCKER_IMAGE_NAME=graphql-schema-registry
  - DOCKER_IMAGE_URL=ycedillos/graphql-schema-registry
stages:
- merge
before_install:
- openssl aes-256-cbc -K $encrypted_66f446734868_key -iv $encrypted_66f446734868_iv
  -in ci-cd/encrypted/keys.tar.gz.enc -out keys.tar.gz -d
- chmod 764 ci-cd/scripts/deployment.sh
jobs:
  include:
  - stage: merge
    if: branch IN (main) AND type = push
    name: Build Container
    script:
    - node -v
    - npm i -g yarn
    - "./ci-cd/scripts/deployment.sh"
