dist: xenial
language: bash
services:
- docker
addons:
  apt:
    packages:
    - docker
branches:
  only:
  - main
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - HELM_VERSION=v3.5.4
  - REGION=us-central1
  - GRAPHQL_REPO_NAME=graphql-schema-registry
  - GRAPHQL_REPO_ORG=pipedrive
  - GRAPHQL_REPO_TAG=1.2.4
  - DOCKER_IMAGE_NAME=graphql-schema-registry
  - DOCKER_IMAGE_URL=ycedillos/graphql-schema-registry
  - DOCKER_COMPOSE_VERSION=1.29.1
stages:
- pull-request
before_install:
- openssl aes-256-cbc -K $encrypted_66f446734868_key -iv $encrypted_66f446734868_iv
  -in ci-cd/encrypted/keys.tar.gz.enc -out keys.tar.gz -d
- chmod 764 ci-cd/scripts/deployment.sh
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
jobs:
  include:
  - stage: pull-request
    if: branch IN (main) AND type IN (push, api, cron)
    name: Pull Request
    script:
    - "./ci-cd/scripts/deployment.sh"
