sudo: required
dist: focal
language: node_js
#services:
#- docker
#addons:
#  apt:
#    packages:
#      - docker
node_js:
- lts/*
branches:
  only:
  - main
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
  global:
  - DOCKER_IMAGE_NAME=trunk_based_development
  - COMMIT=${TRAVIS_COMMIT::8}
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - DOCKER_COMPOSE_VERSION=1.29.1
stages:
- build
- merge
- manual_deployment
before_install:
- chmod 764 ci-cd/scripts/environment-deployment.sh
#- sudo rm /usr/local/bin/docker-compose
#- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#- chmod +x docker-compose
#- sudo mv docker-compose /usr/local/bin
cache:
  yarn: true
  directories:
  - node_modules
jobs:
  include:
  - stage: build
    if: branch IN (main) AND type = pull_request
    name: Build
    #install:
    #- node -v
    #- npm i -g yarn
    #- yarn install
    script:
    #- yarn build
    - echo "Pull Request"
    - echo "TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}"
    - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
  - stage: merge
    if: branch IN (main) AND type = push AND tag IS NOT present
    name: Build Container
    script: 
    # - "./ci-cd/scripts/environment-deployment.sh"
    - echo "Merge"
    - echo "TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}"
    - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
  - stage: manual_deployment
    if: tag IS present
    name: Manual Deployment
    script: 
    #- "./ci-cd/scripts/environment-deployment.sh"
    - echo "GIT TAG"
    - echo "TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}"
    - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
