version: "3.8"

services:
  trunk-based-development:
    container_name: trunk_based_development
    build:
      context: .
      dockerfile: ./ci-cd/docker/Dockerfile
    command: yarn start
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - demo-network
    volumes:
      - ".:/app"
      - "/app/node_modules"
    restart: unless-stopped

networks:
  demo-network:
    driver: bridge